### ISSUE TITLE
Racc::ParseError with pronto-fasterer but not standalone fasterer

### ISSUE THREAD

**Issue by dankohn** [prontolabs/pronto-fasterer#7]
I'm getting an error when running fasterer with pronto but not when run standalone. Conveniently, the project is open source and the issue is with this [branch](https://github.com/linuxfoundation/cii-best-practices-badge/compare/dan-fasterer).

Here's a look at the error:
```sh
cii-best-practices-badge (dan-fasterer)$ fasterer
app/models/criteria.rb
Array#reverse.each is slower than Array#reverse_each. Occurred at lines: 140.

app/models/project.rb
Using each_with_index is slower than while loop. Occurred at lines: 188.
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 287.

test/models/criteria_test.rb
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 64, 75.

185 files inspected, 5 offenses detected


cii-best-practices-badge (dan-fasterer)$ pronto run -r fasterer --commit=$(git log --pretty=format:%H | tail -1)
/Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:528:in `on_error': (string):53 :: parse error on value ["END", 53] (klEND) (Racc::ParseError)
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.9.0/lib/ruby_parser_extras.rb:1163:in `on_error'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.9.0/lib/ruby_parser_extras.rb:1075:in `block in process'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:33:in `catch'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.9.0/lib/ruby_parser_extras.rb:1063:in `process'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fasterer-0.3.2/lib/fasterer/parser.rb:8:in `parse'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fasterer-0.3.2/lib/fasterer/analyzer.rb:21:in `scan'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-fasterer-0.9.0/lib/pronto/fasterer.rb:17:in `inspect'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-fasterer-0.9.0/lib/pronto/fasterer.rb:12:in `block in run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-fasterer-0.9.0/lib/pronto/fasterer.rb:12:in `map'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-fasterer-0.9.0/lib/pronto/fasterer.rb:12:in `run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/lib/pronto/runners.rb:20:in `block in run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/lib/pronto/runners.rb:13:in `each'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/lib/pronto/runners.rb:13:in `run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/lib/pronto.rb:64:in `run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/lib/pronto/cli.rb:61:in `block in run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `chdir'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/lib/pronto/cli.rb:60:in `run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/dan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pronto-0.9.3/bin/pronto:6:in `<top (required)>'
	from /Users/dan/.rbenv/versions/2.4.1/bin/pronto:22:in `load'
	from /Users/dan/.rbenv/versions/2.4.1/bin/pronto:22:in `<main>'
```
I had previously run into issues with fasterer not working with Ruby 2.4 due to [ruby_parser](https://github.com/seattlerb/ruby_parser/issues/239), but that seems resolved. I'm unclear why the way I'm calling it from pronto would produce different results.

Thanks in advance.

Cc @david-a-wheeler

**Comment by mmozuras** [comment]
The offending commit seems to be `HEAD~325` (`HEAD` = `master` = `c5c439f6`). Up to `HEAD~324` Pronto works correctly. 

Error: 

```bash
➜  cii-best-practices-badge git:(master) pronto run -r fasterer --commit=HEAD~325
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:528:in `on_error': (string):53 :: parse error on value ["END", 53] (klEND) (Racc::ParseError)
	from /usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.9.0/lib/ruby_parser_extras.rb:1163:in `on_error'
	from /usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `_racc_do_parse_c'
	from /usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/racc/parser.rb:259:in `do_parse'
```

No error:

```bash
➜  cii-best-practices-badge git:(master) pronto run -r fasterer --commit=HEAD~324
app/models/criteria.rb:140 W: Array#reverse.each is slower than Array#reverse_each
app/models/project.rb:188 W: Using each_with_index is slower than while loop
app/models/project.rb:287 W: Hash#keys.each is slower than Hash#each_key
test/models/criteria_test.rb:64 W: Hash#keys.each is slower than Hash#each_key
test/models/criteria_test.rb:75 W: Hash#keys.each is slower than Hash#each_key
```

Note that when you run Pronto the way you do, you run it on the whole repository history. While `fasterer` works fine on current code, historical code might not work be supported. I don't see this a way to fix it in Pronto 🙂.

@dankohn what do you think? Does it clear it up?

**Comment by dankohn** [comment]
@mmozuras thanks for your investigation. `--commit=$(git log --pretty=format:%H | tail -1)` always seemed overly verbose for just saying that I want to run the linters across the entire codebase (not the entire history). Am I doing it wrong?

**Comment by mmozuras** [comment]
@dankohn running Pronto in the default mode should be enough for most cases. That runs Pronto against the whole codebase, but only those part of the codebase that changed. 

It might be worth running Pronto for the whole history once. Afterward, you can just run it in default mode again (comparing a new branch against `master`). Or configure it to run for the latest commit 🙂.
