### ISSUE TITLE
Racc::ParseError: (string):69 :: parse error on value "[" (tLBRACK2)

### ISSUE THREAD

**Issue by rderoldan1** [prontolabs/pronto-fasterer#8]
I don't know if this error is related to #7, but I'm getting the following error with ruby 2.5.5

```log
bundler: failed to load command: pronto (/Users/ruben/.rbenv/versions/2.5.5/bin/pronto)
Racc::ParseError: (string):69 :: parse error on value "[" (tLBRACK2)
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/ruby_parser-3.13.0/lib/ruby_parser_extras.rb:1162:in `on_error'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/racc/parser.rb:259:in `do_parse'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/ruby_parser-3.13.0/lib/ruby_parser_extras.rb:1069:in `block in process'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/timeout.rb:33:in `catch'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/ruby_parser-3.13.0/lib/ruby_parser_extras.rb:1057:in `process'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fasterer-0.5.1/lib/fasterer/parser.rb:8:in `parse'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/fasterer-0.5.1/lib/fasterer/analyzer.rb:21:in `scan'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-fasterer-0.10.0/lib/pronto/fasterer.rb:17:in `inspect'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-fasterer-0.10.0/lib/pronto/fasterer.rb:12:in `block in run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-fasterer-0.10.0/lib/pronto/fasterer.rb:12:in `map'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-fasterer-0.10.0/lib/pronto/fasterer.rb:12:in `run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/lib/pronto/runners.rb:20:in `block in run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/lib/pronto/runners.rb:13:in `each'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/lib/pronto/runners.rb:13:in `run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/lib/pronto.rb:64:in `run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/lib/pronto/cli.rb:66:in `block in run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `chdir'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/lib/pronto/cli.rb:64:in `run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/ruben/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pronto-0.10.0/bin/pronto:6:in `<top (required)>'
  /Users/ruben/.rbenv/versions/2.5.5/bin/pronto:23:in `load'
  /Users/ruben/.rbenv/versions/2.5.5/bin/pronto:23:in `<top (required)>'
```

**Comment by mmozuras** [comment]
@rderoldan1 do you have a way to reproduce this issue? Is the repo you run on it open source? Or maybe you could recreate the issue on a new repo?

**Comment by ashkulz** [comment]
Guessing that no response from @rderoldan1 means it's probably not relevant, so closing for now. Feel free to reopen it if you can provide more details :+1:
